sudo: required

before_install:
    - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-add-repository -y ppa:beineri/opt-qt542
    - sudo apt-get -qq update

install:
    - sudo apt-get -qq install g++-4.8 libc6-i386 qt54tools qt54svg qt54webkit qt54serialport
    - PATH="/opt/qt54/bin:$PATH"
    - qt54-env.sh 
    - wget https://sourceforge.net/projects/qwt/files/qwt/6.1.2/qwt-6.1.2.tar.bz2/download
    - ls
    - tar -xvjf qwt-6.1.2.tar.bz2
    - cd qwt-6.1.2
    - qmake qwt.pro
    - sudo make install
    - cd ../

script:
    - qmake
    - make

language: cpp
