sudo: required

before_install:
    - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-add-repository -y ppa:beineri/opt-qt542
    - sudo apt-get -qq update

install:
    - sudo apt-get -qq install g++-4.8 libc6-i386 qt54tools qt54svg qt54webkit qt54serialport
    - PATH="/opt/qt54/bin:$PATH"
    - qt54-env.sh 
    - wget -q http://heanet.dl.sourceforge.net/project/qwt/qwt/6.1.3/qwt-6.1.3.tar.bz2
    - tar -xvf  qwt-6.1.3.tar.bz2
    - cd qwt-6.1.3
    - qmake qwt.pro
    - sudo make
    - sudo make install
    - cd ../

script:
    - qmake
    - make

language: cpp
